spring:
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/WeCaht?useUnicode=true&characterEncoding=utf-8
    username: root
    password: chenyoyo
server:
  tomcat:
  uri-encoding: UTF-8

#mybaties
#api配置
openApi:
  meizuWeather:
    url: http://aider.meizu.com/app/weather/listWeather
    requestType: GET
    params1: cityIds
  xiaomiWeather: https://weatherapi.market.xiaomi.com/wtr-v3/weather/all
  express100:
    url: http://www.kuaidi100.com/query
    requestType: GET
    params1: type
    params2: postid
  bingdict:
    url: https://dict.bing.com.cn/api/http/v2/4154AA7A1FC54ad7A84A0236AA4DCAF3/en-us/zh-cn/
    requestType: GET
    params1: q
    params2: format
    jsonFormat: application/json
    xmlFormat: application/xml
#微信配置
WeChat:
  access_token:
    url: https://api.weixin.qq.com/cgi-bin/token
    params1:
     key: grant_type
     value: client_credential
    params2:
      key: appid
      value: wxb72cc46de21b5c13
    params3:
      secret: 58536fcbb358b58c6ca042ca431cf7f6
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.imchen.mapper
#图灵api
TuLing:
  api:
    url: http://www.tuling123.com/openapi/api
    key: 3e5ec66738e561e94deaf5af11259c26
    secret: e5e84686d09afbf2
    param1: key
    param2: text
